### ISSUE TITLE
help building  on linux 

### ISSUE THREAD

**Issue by cyrstem** [andydbc/Dot#1]
hi for some reason when trying to  cmake on linux i got this  error when running make any idea to fix this ?

[ 84%] Building CXX object CMakeFiles/Dot.dir/src/RtMidi.cpp.o
/home/jacos/Apps/Dot/src/RtMidi.cpp:2358:10: fatal error: windows.h: No such file or directory
 2358 | #include <windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Dot.dir/build.make:63: CMakeFiles/Dot.dir/src/RtMidi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: CMakeFiles/Dot.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by andydbc** [comment]
I was mostly testing it on windows, will update the code shortly

**Comment by cyrstem** [comment]
thanks!!!

**Comment by andydbc** [comment]
From d7e17d6abadbaa6cd0795309b8b8382cf7ae8a15, you should be able to compile on Linux
